#!/usr/bin/env python3
"""Build the C4Bridge Control4 driver package.

VERSION is the only version source. The build stamps it into the packaged driver
(driver.xml <version> and src/core/version.lua) and embeds the OpenAPI document from
api/openapi.yaml so the driver can serve it at /v1/openapi.json.

Outputs:
  dist/C4Bridge.c4z   the driver package
  dist/openapi.json   the API description for this version
"""

import json
import re
import sys
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

import yaml

ROOT = Path(__file__).resolve().parents[1]
DRIVER = ROOT / "driver"
SPEC = ROOT / "api" / "openapi.yaml"
DIST = ROOT / "dist"
PACKAGE = DIST / "C4Bridge.c4z"
SPEC_JSON = DIST / "openapi.json"

VERSION_PATTERN = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")
SOURCE_VERSION_LINE = 'Version.BRIDGE_VERSION = "dev"'
SPEC_MODULE = "src/api/openapi_spec.lua"

# Fixed timestamp so the same source always produces the same package bytes.
ZIP_DATE = (2026, 1, 1, 0, 0, 0)


def fail(message):
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_version():
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    match = VERSION_PATTERN.match(version)
    if not match:
        fail(f"VERSION must be MAJOR.MINOR.PATCH (e.g. 0.2.0), got {version!r}")
    major, minor, patch = (int(part) for part in match.groups())
    if minor > 99 or patch > 99:
        fail("minor and patch must be below 100 so the Control4 driver version stays increasing")
    return version, major * 10000 + minor * 100 + patch


def stamped_driver_xml(driver_version):
    source = (DRIVER / "driver.xml").read_text(encoding="utf-8")
    stamped, count = re.subn(r"<version>\d+</version>", f"<version>{driver_version}</version>", source)
    if count != 1:
        fail("driver.xml must contain exactly one <version> element")
    return stamped


def stamped_version_lua(version):
    source = (DRIVER / "src" / "core" / "version.lua").read_text(encoding="utf-8")
    if source.count(SOURCE_VERSION_LINE) != 1:
        fail(f"src/core/version.lua must contain {SOURCE_VERSION_LINE!r} for stamping")
    return source.replace(SOURCE_VERSION_LINE, f'Version.BRIDGE_VERSION = "{version}"')


def load_spec(version):
    spec = yaml.safe_load(SPEC.read_text(encoding="utf-8"))
    spec["info"]["version"] = version
    return spec


def spec_module(spec):
    document = json.dumps(spec, ensure_ascii=False, separators=(",", ":"))
    # Level 0 long strings reject a nested "[[" in Lua 5.1, so start at level 1.
    level = 1
    while f"]{'=' * level}]" in document or f"[{'=' * level}[" in document:
        level += 1
    equals = "=" * level
    return (
        "-- Generated by scripts/build.py from api/openapi.yaml. Do not edit.\n"
        f"return [{equals}[{document}]{equals}]\n"
    )


def package_entries(version, driver_version, spec):
    entries = {
        "driver.xml": stamped_driver_xml(driver_version),
        "driver.lua": (DRIVER / "driver.lua").read_text(encoding="utf-8"),
    }
    for path in sorted((DRIVER / "src").rglob("*.lua")):
        name = path.relative_to(DRIVER).as_posix()
        entries[name] = path.read_text(encoding="utf-8")
    if SPEC_MODULE in entries:
        fail(f"{SPEC_MODULE} is generated; remove it from the source tree")
    entries["src/core/version.lua"] = stamped_version_lua(version)
    entries[SPEC_MODULE] = spec_module(spec)
    return entries


def write_package(entries):
    DIST.mkdir(parents=True, exist_ok=True)
    with ZipFile(PACKAGE, "w", compression=ZIP_DEFLATED) as archive:
        for name in sorted(entries):
            info = ZipInfo(name, date_time=ZIP_DATE)
            info.compress_type = ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, entries[name].encode("utf-8"))


def main():
    version, driver_version = read_version()
    spec = load_spec(version)
    write_package(package_entries(version, driver_version, spec))
    SPEC_JSON.write_text(json.dumps(spec, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Built {PACKAGE} (version {version}, Control4 driver version {driver_version})")
    print(f"Wrote {SPEC_JSON}")


if __name__ == "__main__":
    main()
